CREATE TABLE IF NOT EXISTS fornecedores (
  id                      SERIAL PRIMARY KEY,
  codfor                  INTEGER NOT NULL UNIQUE,
  nome                    VARCHAR(255) NOT NULL,
  apelido                 VARCHAR(150),
  fone1                   VARCHAR(20),
  fone2                   VARCHAR(20),
  whatsapp                VARCHAR(20),
  celular                 VARCHAR(20),
  tabela                  VARCHAR(50),
  concorrente             VARCHAR(50),
  status_ok               VARCHAR(10),
  dias                    INTEGER DEFAULT 0,
  ultima_entrega          DATE,
  tipo_pessoa             CHAR(1), -- F ou J
  data_cadastro           DATE,
  endereco                VARCHAR(255),
  numero                  VARCHAR(20),
  complemento             VARCHAR(150),
  bairro                  VARCHAR(150),
  cidade                  VARCHAR(150),
  uf                      CHAR(2),
  cep                     VARCHAR(10),
  cnpj                    VARCHAR(18),
  ie                      VARCHAR(30),
  im                      VARCHAR(30),
  rg                      VARCHAR(20),
  emissor                 VARCHAR(20),
  cpf                     VARCHAR(14),
  comprador               VARCHAR(150),
  email                   VARCHAR(150),
  condicao_pagamento      VARCHAR(50),
  usuario_cadastro        VARCHAR(100),
  ultimo_alterou          VARCHAR(100),
  dias_atraso             INTEGER DEFAULT 0,
  dias_previsao           INTEGER DEFAULT 0,
  filial                  VARCHAR(50),
  criado_em               TIMESTAMP DEFAULT NOW(),
  atualizado_em           TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fornecedores_cnpj ON fornecedores (cnpj);
CREATE INDEX IF NOT EXISTS idx_fornecedores_nome ON fornecedores (nome);
