CREATE TABLE IF NOT EXISTS fornecedores (
  id                      SERIAL PRIMARY KEY,
  codfor                  INTEGER NOT NULL UNIQUE,
  nome                    TEXT NOT NULL,
  apelido                 TEXT,
  fone1                   TEXT,
  fone2                   TEXT,
  whatsapp                TEXT,
  celular                 TEXT,
  tabela                  TEXT,
  concorrente             TEXT,
  status_ok               TEXT,
  dias                    INTEGER DEFAULT 0,
  ultima_entrega          DATE,
  tipo_pessoa             TEXT,
  data_cadastro           DATE,
  endereco                TEXT,
  numero                  TEXT,
  complemento             TEXT,
  bairro                  TEXT,
  cidade                  TEXT,
  uf                      TEXT,
  cep                     TEXT,
  cnpj                    TEXT,
  ie                      TEXT,
  im                      TEXT,
  rg                      TEXT,
  emissor                 TEXT,
  cpf                     TEXT,
  comprador               TEXT,
  email                   TEXT,
  condicao_pagamento      TEXT,
  usuario_cadastro        TEXT,
  ultimo_alterou          TEXT,
  dias_atraso             INTEGER DEFAULT 0,
  dias_previsao           INTEGER DEFAULT 0,
  filial                  TEXT,
  criado_em               TIMESTAMP DEFAULT NOW(),
  atualizado_em           TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fornecedores_cnpj ON fornecedores (cnpj);
CREATE INDEX IF NOT EXISTS idx_fornecedores_nome ON fornecedores (nome);
