CREATE TABLE IF NOT EXISTS clientes (
  id                      SERIAL PRIMARY KEY,
  codigo                  INTEGER NOT NULL UNIQUE,
  nome                    VARCHAR(255) NOT NULL,
  fantasia                VARCHAR(255),
  telefone1               VARCHAR(150),
  telefone2               VARCHAR(150),
  dias                    INTEGER DEFAULT 0,
  ultima_saida            DATE,
  endereco                VARCHAR(255),
  numero                  VARCHAR(150),
  bairro                  VARCHAR(150),
  cidade                  VARCHAR(150),
  uf                      VARCHAR(10),
  pais                    VARCHAR(100),
  cep                     VARCHAR(20),
  cnpj                    VARCHAR(30),
  ie                      VARCHAR(100),
  cpf                     VARCHAR(30),
  rg                      VARCHAR(100),
  tipo_cliente            VARCHAR(100),
  contato_comercial       VARCHAR(150),
  contato_financeiro      VARCHAR(150),
  status                  VARCHAR(50),
  email                   VARCHAR(255),
  usuario_cadastro        VARCHAR(150),
  ultimo_alterou          VARCHAR(150),
  vendedor                VARCHAR(150),
  atualizado              DATE,
  filial                  VARCHAR(100),
  criado_em               TIMESTAMP DEFAULT NOW()
);
