CREATE TABLE IF NOT EXISTS clientes (
  id                      SERIAL PRIMARY KEY,
  codigo                  INTEGER NOT NULL UNIQUE,
  nome                    TEXT NOT NULL,
  fantasia                TEXT,
  telefone1               TEXT,
  telefone2               TEXT,
  dias                    INTEGER DEFAULT 0,
  ultima_saida            DATE,
  endereco                TEXT,
  numero                  TEXT,
  bairro                  TEXT,
  cidade                  TEXT,
  uf                      TEXT,
  pais                    TEXT,
  cep                     TEXT,
  cnpj                    TEXT,
  ie                      TEXT,
  cpf                     TEXT,
  rg                      TEXT,
  tipo_cliente            TEXT,
  contato_comercial       TEXT,
  contato_financeiro      TEXT,
  status                  TEXT,
  email                   TEXT,
  usuario_cadastro        TEXT,
  ultimo_alterou          TEXT,
  vendedor                TEXT,
  atualizado              DATE,
  filial                  TEXT,
  criado_em               TIMESTAMP DEFAULT NOW()
);
